/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TProtocolFactory.h"
#import "TApplicationError.h"
#import "TProtocolError.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TBaseClient.h"

#import "Jaeger.h"

@protocol Agent <NSObject>
- (BOOL) emitBatch: (Batch *) batch error: (NSError *__autoreleasing *)__thriftError;  // throws TException
@end

@interface AgentClient : TBaseClient <Agent> 
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface AgentProcessor : NSObject <TProcessor> 
- (id) initWithAgent: (id <Agent>) service;
- (id<Agent>) service;
@end

FOUNDATION_EXPORT NSString *AgentErrorDomain;


